fangq/mcx

example/multipattern/multipattern.json
mcxlab/examples/demo_photon_sharing.m
mcxlab/mcxlab.m
src/mcx_core.cu
src/mcx_utils.c
src/mcx_utils.h

1. implement normalization for multi-pattern and update the corresponding command window printing
2. for multi-pattern, add mcx_kahanSum function to accumulate a sequence of finite precision floating point numbers
3. update the photon sharing demo: issrcfrom0 should be set to 1 for multi-pattern
4. fix incorrect output field for one source pattern
5. fix mcxlab 'gpuinfo' output error when there are multiple GPUs

modify post-processing to support normalization of multi-pattern

---

src/mcxlab.cpp

https://github.com/fangq/mcx/commit/7e45ec04de9575e405411ae3d01c7c0b2ef0df3a In this commit, MCX is updated to produce detected photon output matches that of MMC, in particular, instead of reporting nscat for all tissue types, MCX reports nscat for each tissue type respectively, but the corresponding part in mcx_replay_prep is not updated and this draws an error in demo_replay_vs_pmc_timedomain.m when the background media are heterogeneous.

fix indexing mismatch between mcx_replay_prep and mcx detphotons output

---

src/mcx_core.cu

Currently, [cfg->energytot is NOT returned to host when cfg->isnormalized is 0](https://github.com/fangq/mcx/blob/43b377a722bc3c0c9ce8aa2ee1ab0c3977725c5f/src/mcx_core.cu#L2079-L2089). As a result, energytot, which will be used in [print](https://github.com/fangq/mcx/blob/43b377a722bc3c0c9ce8aa2ee1ab0c3977725c5f/src/mcx_core.cu#L2230-L2234), can not be evaluated properly for multiple patterns.
Meanwhile, for photon sharing, cfg->energytot==cfg->nphoton is always true when cfg->srcnum>1. Therefore here we replace cfg->energytot using cfg->nphoton to solve the above issue.

fix print information for multiptle patterns when cfg.isnormalized==0

---

utils/mcxmeanpath.m

Hi Dr. Fang,
I think the mcxmeanpath.m function also needed to be modified, besides mcxdetweight.m. When I calculated the mean pathlength, I had to multiply detp.ppath by unitinmm before I throw them into the function mcxmeanpath. Now the mcxdetweight.m takes unitinmm into consideration, should I change the mcxmeanpath.m function like below? I modified the code and the result looks correct.

consider unitinmm in "mcxmeanpath.m"

---

mcxlab/mcxpreview.m

Fix the orientation of the source plane.
Not rotate the quadrilateral by srcdir while using planar or pattern source type.
For example, in the `demo_photon_sharing.m`, if I set the srcparam1 and srcparam2 like that, the preview will be not consistent with the setting.
But the simulation result will be consistent with the setting.
After change a little bit in `mcxpreview.m`, the preview will be consistent with the setting.

fix preview for pattern source etc.

---

mcxcloud/frontend/index.html

This commit adds three new features to the volumetric renderer in MCX Cloud:
- Isosurface rendering: the user may now choose whether to view a MIP or an isosurface. The isosurface rendering shader taken from Three.js has been modified and optimized to allow for faster ray marching.
- Cross sectional views: the user may define a subset of the data within a bounding box to view, allowing for cross-sectional rendering of geometry. The rendering shaders have been modified to allow for cross-sectional views.
- Orthonormal viewing axes: the user can now choose a coordinate axis with which to align the camera.
Please let me know if there are any questions or concerns regarding this pull request!

Add isosurface rendering, cross sectional viewing planes, and orthonormal viewing axes

---

src/mcx_core.cu

line#604: _floorf(p->x,y,z)_ can no longer represent voxel indices after removing _my_nextafterf_;
line#648: _p0_ is the original position, should be changed to the position after moving _len_;
line#1669-1671: no need to update voxel indices if ray intersects with intra-voxel boundary.

fix svmc issue after patch f8da832f11b751c07d33c77dd7d428a2c75a888b

---

.travis.yml
mcxlab/examples/demo_polarized_photon.m
src/mcx_core.cu
utils/json2mcx.m
utils/mcxcwdref.m

Inspired by @DouglasDwyer's DDA ray-marching shader code, I was able to get rid of `mcx_nextafter` in the ray-voxel intersection function `hitgrid()`. This reduces the registered counts across most of the template-specialized kernels, about ~8 register less for half of the kernels.
as a result, the simplest kernel - pencil-beam-source with no reflection as in `mcx --bench cube60` - achieved 40% higher speed - this is one of the most significant optimization-resulting speed-up we have seen over the past few years. 
Unfortunately this reduction does not shorten runtimes of other simulations, but if we can further cut down registers (by 6-8 more), we anticipate this will eventually reach the threshold to bring significant speed up.

Reducing register counts using simplified hitgrid, speed up cube60 by 40%

---

README.md
src/CMakeLists.txt
src/mcx_utils.c
src/mcx_utils.h
src/pymcx.cpp
src/setup.py

Hello,
These new changes has better type checking of inputs and error handling that will show up as native Python errors. The errors have more informative messages for the user to understand the cause.
Please check the try/catch exception clause for MCX's OpenMP launch for correctness and absence of race conditions. Instead of a simple error_flag integer being shared between threads, a vector of strings is shared so that if an error occurs, all of their error messages will be concatenated and thrown to Python as a single runtime error.
Thanks

Additional error/input checking for PyMCX + Better error propagation

---

src/pymcx.cpp

This PR removes the restriction of the input volumes to PyMCX being C_Style, accepting both C_Style (usually created inside Python) and F_Style (usually created in MATLab and Octave).

Removed restriction on volumes being C_Style in PyMCX

---

src/mcx_core.cu

Dear Prof. Fang,
I was playing with MCXlab at low absorption values, but it seems that below a certain threshold the fluence fails numerically and becomes eventually zero. The threshold can be lowered by turning on the `DUSE_DOUBLE` and `DUSE_MORE_DOUBLE` flags, but in principle the correct limit for low absorption is simply obtained by accumulating the appropriate Taylor expansion for the exponential `w0 * (1 - exp(-prop.mua * len)) / prop.mua`.
To take advantage of this one can introduce an `if` condition depending on the `prop.mua / prop.mus` ratio instead of the currently implemented zero value for `prop.mua == 0`. See the picture below relative to a homogeneous medium.
The dashed line value is calculated as the average pathlength in the medium (which is given by [line 1894 of …

fix fluence for mua -> 0

---

mcxcloud/frontend/index.html
mcxlab/examples/demo_mcxlab_srctype.m
mcxstudio/mcxsource.lfm
schema/mcxinput.json
src/mcx_const.h
src/mcx_core.cu
src/mcx_utils.c
src/mcx_utils.h
src/mcxlab.cpp
src/pmcx.cpp
utils/mcxpreview.m

@leoyala, here is my simplified implementation for the ring/ring sector source you proposed in #181. I reused most of the code in the `disk` source and this patch does not introduce additional registers.
I am not fully sure I understand your `srcparam1.z/w` settings. can you explain? in my implementation, .z/.w are simply lower and higher bound of the ring angle.
also, can you explain your `srcparam2.x`? mcx already uses `cfg.srcdir(4)` as the focal length (negative flocal length generates a diverging beam), I am wondering if `srcdir(4)` is sufficient to simulate the effect you desired.

compact implementation of ring source, close #181

---

src/pmcx.cpp

- apply this factor for `MEDIA_AS_F2H`, `MEDIA_MUA_FLOAT` volume types
- behaviour now matches that of `mcx_loadvolume()` from `mcx_utils.c`
- see #185

add `unitinmm` factor to pmcx `parseVolume()`

---

pmcx/setup.py
src/mcx_core.cu

- If `MCX_DISABLE_CUDA_DEVICE_RESET` is defined then `cudaDeviceReset()` calls are not made in mcx_core.cu
- cudaDeviceReset() destroys all resources on the GPU associated with the current process
- for pmcx this can leave other python GPU libraries like pytorch in a broken state
- resolves #187

Disable `cudaDeviceReset()` calls in pmcx

---

src/pmcx.cpp

- mcx_config.bc has type char[12], with no null terminator required
- resolves #191

Fix buffer overflow error when bc has 12 characters

---

src/mcx_core.cu

- `param2.x`: width of gaussian broadening in direction perpendicular to both slit and v
- `param2.y`: width of gaussian broadening in direction of slit
- resolves #213

Add gaussian broadening to SLIT source

---

mcxlab/mcxlab.m

Following suggestion from @ShijieYan, this commit fixes the wrong ordering of the `traj.iquv` output in polarized simulations.

Fix data ordering in traj.iquv

---

src/pmcx.cpp

- Parse issavedet field of the cfg dict as an int instead of a bool.
Before you submit your pull-request, please verify and check all below items
If your commits included in this PR contain changes that did not follow the above guidelines, you are strongly recommended to create a clean patch using `git rebase` and `git cherry-pick` to prevent in-compliant history from appearing in the upstream code.
Moreover, you are highly recommended to 
- Add a test in the `mcx/test/testmcx.sh` script, following existing examples, to test the newly added feature; or add a MATLAB script under `mcxlab/examples` to gives examples of the desired outputs
- MCX's simulation speed is currently limited by the number of GPU registers. In your change, please consider minimizing the use of registers by reusing …

Change issavedet Flag to Be Parsed as an Int in PMCX

---

pmcx/pmcx/utils.py

fixed fix typo cfg.issaveexit to cfg["issaveexit"], got error when run pmcx.mcxlab(cfg)

fix typo cfg.issaveexit to cfg["issaveexit"]

---

ChangeLog.txt
README.md
src/mcx_core.cu
test/testmcx.sh

Before you submit your pull-request, please verify and check all below items
If your commits included in this PR contain changes that did not follow the above guidelines, you are strongly recommended to create a clean patch using `git rebase` and `git cherry-pick` to prevent in-compliant history from appearing in the upstream code.
Moreover, you are highly recommended to 
- Add a test in the `mcx/test/testmcx.sh` script, following existing examples, to test the newly added feature; or add a MATLAB script under `mcxlab/examples` to gives examples of the desired outputs
- MCX's simulation speed is currently limited by the number of GPU registers. In your change, please consider minimizing the use of registers by reusing existing ones. CUDA compilers may not be able to optimize register …

Fix wrong source type not raise
